### PR TITLE
Put clone() to where it is needed

### PR DESCRIPTION
**Pull request by whs-dot-hk**
Closes: #XXX

## Description
Put clone() to where it is needed

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Review by romac — COMMENTED** [review]
In general if a function requires unconditional ownership of a value, it should make this explicit in its signature and take an owned type. That said, in this case it doesn't hurt too much to do it third way so I'll leave it up to @ljoss17 to decide which version he prefers.

**Comment by ljoss17** [comment]
Let's go with this solution as it looks a bit cleaner

**Comment by whs-dot-hk** [comment]
Applied cargo fmt

**Review by ljoss17 — APPROVED** [review]
Thank you for the work!

**Review by romac — APPROVED** [review]

**Pull request merged**
