### PR TITLE
Add REST endpoint `/clear_packets` to trigger packet clearing

### PR DESCRIPTION
**Pull request by romac**
Closes: #3398

## Description
Add a `/clear_packets?chain=CHAIN_ID` endpoint to the built-in REST server to trigger packet clear for the chain specified in the `chain` query param or for all chains if the query param is omitted.

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by puneet2019** [comment]
hey @romac , is there any way, and can it be added? 
/clear-packets/{channel-id}/{sequence_number} - to clear a single specific packet.
Rest and CLI both.

**Comment by romac** [comment]
@puneet2019 Tracked here: https://github.com/informalsystems/hermes/issues/3672

Unfortunately I can't promise a timeline for when we can get to it as we have very limit d bandwidth until next year.

**Comment by taitruong** [comment]
Hi, I've been testing this on 1.7.0 - but seems not to be released yet? Tried these:

http://localhost:3000/clear_packets?chain_id=pisco-1
http://localhost:3000/clear_packets?chain=pisco-1

None works - endpoint seems not to be avaiable. http://localhost:3000/state works though

**Comment by taitruong** [comment]
just tested with 1.7.1 
http://localhost:3001/clear_packets returns 404

**Pull request merged**
