### PR TITLE
Set channel version at the application level 

### PR DESCRIPTION
**Pull request by seanchen1991**
Closes: #3213 

## Description

______

### PR author checklist:
- [ ] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [ ] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by romac** [comment]
Perhaps we should actually keep the counterparty version set in the OpenTry message and see if that fixes some tests.

The ordered channel is apparently using an old version of ibc-go (v3) which seems to require the version at the open init step. We should see if we can update it to a newer version.

**Comment by romac** [comment]
Nevermind, looks like pretty much all tests are failing, even on Gaia 8. Maybe we should just drop this PR then, or at least clarify the expected behavior with the ibc-go team.

**Comment by romac** [comment]
Looks like gaia8 (and likely other chains using the same ibc-go version) still expects a version to be set at chan open init, so perhaps we should keep doing that as well.

**Comment by romac** [comment]
Given the resulting change I wonder if we shouldn't just drop the PR altogether? Do we foresee any issues with setting the try version to its init counterpart? If not then let's drop it.

**Comment by ljoss17** [comment]
I agree, the deprecated version in the `Channel` field doesn't seem to bring much to Hermes. I would be keen to drop this PR

**Pull request closed without merging**
