### PR TITLE
Use workspace dependencies

### PR DESCRIPTION
**Pull request by DaviRain-Su**
Closes: #3104 

## Description

according to rust verison 1.64.0 https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html#cargo-improvements-workspace-inheritance-and-multi-target-builds , we can use this feature.

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by romac** [comment]
Great stuff, I have been meaning to do this for a while so thanks a lot for doing this! We'll wait a bit to merge this until we get in a couple of open PRs which introduce new or updates dependencies.

**Comment by romac** [comment]
@DaviRain-Su Do you know if Dependabot is able to deal with workspace dependencies?

**Comment by DaviRain-Su** [comment]
> @DaviRain-Su Do you know if Dependabot is able to deal with workspace dependencies?

oh, not very clear. I have seen several projects do this. 
- aptos: https://github.com/aptos-labs/aptos-core/blob/main/Cargo.toml
- subxt: https://github.com/paritytech/subxt/pull/832

**Comment by DaviRain-Su** [comment]
> @DaviRain-Su Do you know if Dependabot is able to deal with workspace dependencies?

https://github.com/paritytech/subxt/blob/master/.github/dependabot.yml Hi, I noticed that Subxt is also using a workspace, and upon reviewing the dependably.yml file, it doesn't require any changes. It seems like this issue can be resolved now.

**Pull request closed without merging**
