### PR TITLE
fix: Add explicit root TLS configuration to gRPC clients

### PR DESCRIPTION
**Pull request by allthatjazzleo**
Closes: #4160

## Description

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [ ] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by allthatjazzleo** [comment]
@romac @ljoss17 
any chance to review it?

**Comment by romac** [comment]
Good catch, thanks for opening this PR, much appreciated! We'll take a look ASAP!

**Comment by romac** [comment]
LGTM, thanks a lot!

**Review by ljoss17 — APPROVED** [review]
Thanks for handling this!

**Comment by romac** [comment]
@allthatjazzleo Can you please add a changelog entry in `.changelog/unreleased/bug-fixes`?

**Comment by allthatjazzleo** [comment]
@romac changelog entry done and resolve conflicts

**Comment by allthatjazzleo** [comment]
@ljoss17 
I rebase from the master  and resolve those conflict from #4102
why do we want to use abci_query instead of grpc?

**Comment by ljoss17** [comment]
> @ljoss17 I rebase from the master and resolve those conflict from #4102 why do we want to use abci_query instead of grpc?

We had issues with this query using the gRPC. And there is a plan to eventually switch to RPC only endpoints.

**Pull request merged**
