### PR TITLE
Small cleanups

### PR DESCRIPTION
**Pull request by romac**

### CODE REVIEW

**Comment by seanchen1991** [comment]
Is this ready for merging?

**Comment by romac** [comment]
Yes!

**Comment by seanchen1991** [comment]
Let's get [this](https://github.com/informalsystems/hermes/pull/3350#discussion_r1212044709) change in here. Then it looks good to me 👍

**Comment by seanchen1991** [comment]
Oh never mind, just realized that PR that introduced the `max_concurrency` parameter was merged into the `romac/remove_runtime` branch.

**Review by seanchen1991 — APPROVED** [review]

**Pull request merged**
