### PR TITLE
Allow for optimistic channel handshake

### PR DESCRIPTION
**Pull request by ancazamfir**
Closes: #2910

## Description
Assuming channel mode is enabled in the hermes configuration.

For the case where a channel is initialized with a connection that is not opened, the approach in this PR is:
- if connection mode is not enabled do not run optimistic channel handshake. This is the same as current behavior.
- if both connection and channel modes are enabled the channel handshake will be triggered and the retry mechanism waits for connection to be established.

The main changes relative to the current implementation:

1. supervisor spawns channel workers on channel events when:
   - current: channel mode is enabled and connection is opened
   - proposal: channel mode is enabled and either connection is opened or connection mode is enabled
2. if both connection and channel modes are enabled, supervisor scans in-progress connection and starts channel workers if channels have been optimistically initialized for those connections
3. channel worker retry strategy is changed to be based on the max block time of the two chains and allow connection handshake to finalize over 10 blocks. This is the same strategy used during the CLI triggered handshake (i.e. `hermes create channel ...`)

Test Case for 1  that occurs during this sequence (`hermes start` creates workers from events):
```
hermes create client --host-chain ibc-0 --reference-chain ibc-1
hermes create client --host-chain ibc-1 --reference-chain ibc-0
hermes start
hermes tx conn-init --dst-chain ibc-0 --src-chain ibc-1 --dst-client 07-tendermint-0 --src-client 07-tendermint-0
hermes tx chan-open-init --dst-chain ibc-0 --src-chain ibc-1 --dst-connection connection-0 --dst-port transfer --src-port transfer
```
Test Case for 2 that occurs during this sequence (`hermes start` creates workers from scanned state):
```
hermes create client --host-chain ibc-0 --reference-chain ibc-1
hermes create client --host-chain ibc-1 --reference-chain ibc-0
hermes tx conn-init --dst-chain ibc-0 --src-chain ibc-1 --dst-client 07-tendermint-0 --src-client 07-tendermint-0
hermes tx chan-open-init --dst-chain ibc-0 --src-chain ibc-1 --dst-connection connection-0 --dst-port transfer --src-port transfer
hermes start
```

Tests:
- Manual tests for Case 1 and Case 2
    - with connection and channel mode enabled: channel is opened
    - with connection mode disabled, channel mode enabled: channel stays in init state
- Integration test for Case 2 with connection and channel mode enabled: channel is eventually opened

Notes: ~~CI fails due to #3006~~

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [x] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [x] Linked to GitHub issue.
- [x] Updated code comments and documentation (e.g., `docs/`).
- [x] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by romac** [comment]
What's the best way to test this?

**Comment by ancazamfir** [comment]
> What's the best way to test this?

Sorry I should have mentioned. I start two chains, create clients, connection and channel in INIT state then start the relayer. The config has connection and channel mode enabled. Here are the commands:
```
hermes create client --host-chain ibc-0 --reference-chain ibc-1
hermes create client --host-chain ibc-1 --reference-chain ibc-0
hermes tx conn-init --dst-chain ibc-0 --src-chain ibc-1 --dst-client 07-tendermint-0 --src-client 07-tendermint-0
hermes tx chan-open-init --dst-chain ibc-0 --src-chain ibc-1 --dst-connection connection-0 --dst-port transfer --src-port transfer
hermes start
```

Let hermes run for a bit then check the channel and connection states and make sure they are opened. 
We should write some integration tests for this.

**Comment by romac** [comment]
> We should write some integration tests for this.

@ancazamfir I am happy to take care of this if you want?

**Comment by ancazamfir** [comment]
> > We should write some integration tests for this.
> 
> @ancazamfir I am happy to take care of this if you want?

That would be great! I just committed something I had locally if you want to take it from there, or just discard and rewrite.

**Comment by ancazamfir** [comment]
I just found that in the case hermes is started before the `chan-open-init` step things won't work. I think restoring channel from event also needs some changes.
Will move back to draft until I figure it out.

**Review by romac — APPROVED** [review]
Fantastic!

**Pull request merged**
