### PR TITLE
fix: fixed minimum-gas-prices healthcheck messages and make it more verbose/clear

### PR DESCRIPTION
**Pull request by freak12techno**
Closes: #3893

## Description

If the chain doesn't support the query for getting minimum gas prices, display a different warning than we have right now, to prevent misleading users.
Other cases (invalid minimum-gas-prices, errors when fetching minimum-gas-prices, golden path) are the same.

______

### PR author checklist:
- [x] Added changelog entry, using [`unclog`](https://github.com/informalsystems/unclog).
- [ ] Added tests: integration (for Hermes) or unit/mock tests (for modules).
- [x] Linked to GitHub issue.
- [ ] Updated code comments and documentation (e.g., `docs/`).
- [x] Tagged *one* reviewer who will be the one responsible for shepherding this PR.

### Reviewer checklist:

- [ ] Reviewed `Files changed` in the GitHub PR explorer.
- [ ] Manually tested (in case integration/unit/mock tests are absent).

### CODE REVIEW

**Comment by freak12techno** [comment]
@romac can you look into it?

**Review by romac — APPROVED** [review]

**Comment by romac** [comment]
Perfect, thank you so much for the PR! 🙏

**Comment by freak12techno** [comment]
@romac I wasn't aware that you can do `match` together with `if` statements inside, thanks for showing it to me, always nice to learn something new!

**Comment by romac** [comment]
Yeah that's a useful feature! By the way, the code was totally fine as is, it's only a very minor nitpick of mine :)

**Comment by freak12techno** [comment]
@romac it makes the code more pretty IMO, so I am all in for having it your way.

**Pull request merged**
